### PR TITLE
Remove modernizr touch detect

### PR DESCRIPTION
**Pull request by lupinskij**
This was originally implemented for the old blog menu, but we not longer
need it for the new menu.

### CODE REVIEW

**Comment by samccone** [comment]
oh yeah? why?

**Comment by lupinskij** [comment]
This was originally implemented for the old menu.

**Comment by sethkrasnianski** [comment]
Sounds reasonable

**Comment by samccone** [comment]
Is there any bower.json or package.json or vendor file that needs to be deleted

**Comment by lupinskij** [comment]
There's still a custom modernizr build included in the vendor scripts detecting js, webgl, no-touch, geolocation, svg, inlinesvg, smil, and svgclippaths. After searching the stylesheets and scripts I don't see any fallbacks using these selectors so I'm going to remove it now.

**Pull request merged**
